### PR TITLE
Add redirect option to index.html (en)

### PR DESCRIPTION
**Pull request by NoPlagiarism**
If `?redirect=0` in URL => do not redirect
Also, changed on all translations (ru, uk, uz) link to english version (so it could be a permalink)

### CODE REVIEW

**Comment by leshark** [comment]
@NoPlagiarism please ping me If I don't review till the end of the day

**Comment by NoPlagiarism** [comment]
@leshark sorry. it's already tomorrow :sweat_smile:

**Comment by BlackYuzia** [comment]
just a question
What about make index.html only with redirections to en.html?
Or that a bad idea for SEO? :eyes:

**Comment by NoPlagiarism** [comment]
> Or that a bad idea for SEO? 👀

I guess it's even bad idea not for Search Optimization. But just as User Experience. Index.html has always been an English page. And nometa.xyz is quite popular and mentionable to change file structure

**Comment by NoPlagiarism** [comment]
> quite popular and mentionable

Just checked Readme. Не напиздел (I didn't lie tho).

**Comment by leshark** [comment]
@NoPlagiarism 
Can you elaborate what is the purpose of adding `?redirect=0` in html?
`<a href="index.html?redirect=0">English version</a>` instead of  `<a href="index.html>English version</a>`

**Comment by BlackYuzia** [comment]
> Can you elaborate what is the purpose of adding ?redirect=0 in html?

This required if you want see en version of website but your locale is ru or uk or any exist, suppose.

**Comment by leshark** [comment]
> > Can you elaborate what is the purpose of adding ?redirect=0 in html?
> 
> This required if you want see en version of website but your locale is ru or uk or any exist, suppose.

Ok, I understand. Another question. What is the meaning of `if (window.location.search &&`?

**Comment by BlackYuzia** [comment]
> Ok, I understand. Another question. What is the meaning of if (window.location.search &&?

Suppose, search could be `null` / `undefined`
That just check.

**Comment by NoPlagiarism** [comment]
> Ok, I understand. Another question. What is the meaning of `if (window.location.search &&`?

To escape uncaught TypeError (`window.location.search.contains is not a function`)

**Comment by NoPlagiarism** [comment]
@BlackYuzia sry. 2 slow. But yeah

**Comment by leshark** [comment]
> This required if you want see en version of website but your locale is ru or uk or any exist, suppose.

I can go to https://nometa.xyz/uk.html and get Ukrainian translation, without any redirect=0. Even though my locale is English. 
@BlackYuzia

**Comment by NoPlagiarism** [comment]
> I can go to https://nometa.xyz/uk.html and get Ukrainian translation

In uk.html there no redirection script. And in the index.html (English) there is one redirection script, that redirects you

You can freely go to translations, but not to index.html (if another locale)

**Comment by leshark** [comment]
Ah, OK. From RU locale redirection is not working to Index not working. I understand now

**Comment by leshark** [comment]
@NoPlagiarism @BlackYuzia If you are interested I created new project for TODO's in nometa.  (https://github.com/leshark/nometa/projects)

**Comment by BlackYuzia** [comment]
Actually, @leshark @NoPlagiarism  I think `window.location.search &&` code destroy any redirect. Because sometimes search is empty string and js take it as `false` in `if`.
How it could be fixed?

```js
window.location.search?.contains?.("redirect=0") 
// but, chain by "abc?.abcd?.()" could not work on old browsers.
```

image

This requires a bit of edit and fix redirect :eyes:

**Comment by NoPlagiarism** [comment]
> code destroy any redirect

Totally my bad. I can create another PR with hotfix or @leshark can [copy working code from no_redirect_hotfix branch](https://github.com/NoPlagiarism/nometa/blob/no_redirect_hotfix/index.html)

To avoid this I add double-check, but without chaining operator (those are not so old versions, someone could still use them)

**Comment by leshark** [comment]
@NoPlagiarism create another PR please with fix

**Pull request merged**
