### PR TITLE
hotfix redirect

### PR DESCRIPTION
**Pull request by NoPlagiarism**
Fixed redirect error from previous PR (#15)

### CODE REVIEW

**Comment by leshark** [comment]
@NoPlagiarism why do we need a console log?

**Comment by NoPlagiarism** [comment]
Yep, sorry for that :sweat_smile:

**Comment by BlackYuzia** [comment]
Looks weird :eyes:

**Comment by BlackYuzia** [comment]
@NoPlagiarism @leshark 

What about this? :eyes:
Too many if blocks.

```js
// if (!window.location.search) redirect();
// else if (!window.location.search.includes("redirect=0")) redirect();

if (!window.location.search.includes("redirect=0")) redirect();

function redirect() {
    const lang = navigator.language || navigator.userLanguage;
    switch (lang) {
        case "uk":
        case "ru":
        case "uz":
            window.location.href = lang + ".html";
        default:
            break;
    }
};
```

UPD: Remove usesless code. @NoPlagiarism why we need first if check?

**Comment by NoPlagiarism** [comment]
@BlackYuzia Sure, it's technically better. 

> why we need first if check?

How I can remember, to avoid some error

**Comment by BlackYuzia** [comment]
> How I can remember, to avoid some error

@NoPlagiarism could you reproduce this error with my code?

**Comment by NoPlagiarism** [comment]
@BlackYuzia  It just don't work. 
In source there `lang.indexOf('ru')`. So if I enter with `navigator.userLanguage=ru-RU`, it can't redirect me. (`uk-UA ≠ uk`)

**Comment by BlackYuzia** [comment]
A bit weird.
In docs I saw what language is only 2 symbols instead of a few

Oh, okey. I check docs again.
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/language

They are say what language could be 2 symbols or 2-2 digits (ru-RU)... shit.
Okey, that means what if else code block should exist :c 

Anyway, use old code but new:
```js
// if (!window.location.search) redirect();
// else if (!window.location.search.includes("redirect=0")) redirect();

if (!window.location.search.includes("redirect=0")) redirect();
```

**Pull request merged**
